# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{easy-table}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = %q{2010-09-25}
  s.description = %q{Makes it easy to add tables to your views using a nice DSL similar to the form helpers}
  s.email = %q{kmandrup@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".rspec",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "easy-table.gemspec",
     "lib/easy-table.rb",
     "lib/easy-table/namespaces.rb",
     "spec/easy-table/table/table_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/easy-table}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple table helper DSL similar to the well known form helpers}
  s.test_files = [
    "spec/easy-table/rails/configure_spec.rb",
     "spec/easy-table/table/body_spec.rb",
     "spec/easy-table/table/caption_spec.rb",
     "spec/easy-table/table/data/table_spec.rb",
     "spec/easy-table/table/footer_spec.rb",
     "spec/easy-table/table/header_spec.rb",
     "spec/easy-table/table/row/cell_spec.rb",
     "spec/easy-table/table/row/data_row_spec.rb",
     "spec/easy-table/table/row/row_spec.rb",
     "spec/easy-table/table/table_spec.rb",
     "spec/easy-table/table/util/tag_spec.rb",
     "spec/easy-table/table/util/util_spec.rb",
     "spec/easy-table/table_model/body_spec.rb",
     "spec/easy-table/table_model/caption_spec.rb",
     "spec/easy-table/table_model/cell_spec.rb",
     "spec/easy-table/table_model/footer_spec.rb",
     "spec/easy-table/table_model/header_spec.rb",
     "spec/easy-table/table_model/row_spec.rb",
     "spec/easy-table/table_model/table_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.0.0.beta.22"])
      s.add_development_dependency(%q<rspec-action_view>, ["~> 0.3.0"])
      s.add_runtime_dependency(%q<r3_plugin_toolbox>, ["~> 0.3.5"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<sugar-high>, ["~> 0.2.10"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.0.0.beta.22"])
      s.add_dependency(%q<rspec-action_view>, ["~> 0.3.0"])
      s.add_dependency(%q<r3_plugin_toolbox>, ["~> 0.3.5"])
      s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_dependency(%q<sugar-high>, ["~> 0.2.10"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.0.0.beta.22"])
    s.add_dependency(%q<rspec-action_view>, ["~> 0.3.0"])
    s.add_dependency(%q<r3_plugin_toolbox>, ["~> 0.3.5"])
    s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
    s.add_dependency(%q<sugar-high>, ["~> 0.2.10"])
  end
end

